/** Required public provider methods, keyed by the canonical capability kind. */
export const EXTENSION_PROVIDER_METHODS = Object.freeze({
  completion: Object.freeze(["provideCompletions"]),
  structuralRegions: Object.freeze([
    "openDocument",
    "applyDocumentChanges",
    "provideRegion",
    "provideRegionDocument",
    "closeDocument",
  ]),
  virtualDocuments: Object.freeze(["provideVirtualDocuments"]),
  documentParser: Object.freeze(["parseDocument"]),
  documentFormatting: Object.freeze(["provideDocumentFormatting"]),
  rangeFormatting: Object.freeze(["provideRangeFormatting"]),
  diagnostics: Object.freeze(["provideDiagnostics"]),
  codeActions: Object.freeze(["provideCodeActions"]),
  fixAll: Object.freeze(["provideFixAll"]),
  debugConfiguration: Object.freeze([
    "provideDebugConfigurations",
    "resolveDebugConfiguration",
  ]),
  debugAdapter: Object.freeze(["provideDebugAdapterDescriptor"]),
  notebookType: Object.freeze(["deserializeNotebook", "serializeNotebook"]),
  notebookKernel: Object.freeze(["provideNotebookKernelDescriptor"]),
  command: Object.freeze(["executeCommand"]),
  agent: Object.freeze(["activate"]),
  aiProvider: Object.freeze(["listModels", "stream", "cancel"]),
  fileSearch: Object.freeze(["provideFileSearchResults"]),
  textSearch: Object.freeze(["provideTextSearchResults"]),
  quickOpen: Object.freeze(["provideQuickOpenResults"]),
  inlineCompletion: Object.freeze(["provideInlineCompletions"]),
  assistedEdit: Object.freeze(["provideAssistedEdits", "streamAssistedEdits"]),
  aiCodeAction: Object.freeze(["provideAICodeActions"]),
  decoration: Object.freeze(["provideDecorations"]),
  documentColor: Object.freeze([
    "provideDocumentColors",
    "provideColorPresentations",
  ]),
  hover: Object.freeze(["provideHover"]),
  preview: Object.freeze(["providePreview"]),
  task: Object.freeze(["provideTasks", "resolveTask"]),
  terminalProfile: Object.freeze([
    "provideTerminalProfiles",
    "resolveTerminalProfile",
  ]),
  scm: Object.freeze(["provideSourceControlState"]),
  projectTemplate: Object.freeze([
    "provideProjectTemplates",
    "resolveProjectTemplate",
  ]),
});
